OLED_ENABLE = yes
LTO_ENABLE = yes
OPT_DEFS += -DRTC_ENABLE -DDS1307_RTC_DRIVER_ENABLE
SRC += rtc.c ds1307.c
I2C_DRIVER_REQUIRED = yes

ENCODER_MAP_ENABLE = yes
ENCODER_ENABLE = yes

LAYER_LOCK_ENABLE = yes
